// <auto-generated />
namespace HrSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addboo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addboo));
        
        string IMigrationMetadata.Id
        {
            get { return "202107290449340_addboo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
